[deps]
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
RandomizedLinAlg = "0448d7d9-159c-5637-8537-fd72090fea46"
TSVD = "9449cd9e-2762-5aa3-a617-5413e99d722e"
